# docker-compose.yml
version: '3'

services:
  serving:
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
    image: ift6758/serving:latest
    ports:
      - "5050:5000"
    environment:
      WANDB_API_KEY: ${WANDB_API_KEY}
  streamlit:
    build:
      context: ./
      dockerfile: ./Dockerfile.streamlit
    image: ift6758/streamlit:latest
    ports:
      - "8501:8501"
    environment:
      WANDB_API_KEY: ${WANDB_API_KEY}
      

     
